import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, URL_API } from '../servicos/api'

const configs = {
  campanhas:{titulo:'Campanhas',api:'/api/campanhas',campos:[['titulo','Titulo'],['descricao','Descricao'],['objetivo','Objetivo'],['dataInicio','Data inicial','date'],['dataFim','Data final','date'],['metaMinima','Meta minima','number']],acoes:['ativar','encerrar','cancelar']},
  oportunidades:{titulo:'Voluntariado',api:'/api/oportunidades',campos:[['titulo','Titulo'],['descricao','Descricao'],['atividade','Atividade'],['vagas','Vagas','number'],['dataAtividade','Data','date'],['horario','Horario'],['local','Local'],['idadeMinima','Idade minima','number'],['requisitos','Requisitos']],acoes:['abrir','encerrar']},
  acoes:{titulo:'Acoes sociais',api:'/api/acoes',campos:[['titulo','Titulo'],['descricao','Descricao'],['objetivo','Objetivo'],['dataInicio','Data inicial','date'],['dataFim','Data final','date'],['local','Local'],['publicoAtendido','Publico atendido'],['estimativaBeneficiados','Estimativa de beneficiados','number']],acoes:['realizar','cancelar']},
  comunicados:{titulo:'Comunicados',api:'/api/comunicados',publica:'/api/comunicados/publicos',campos:[['titulo','Titulo'],['conteudo','Conteudo'],['tipo','Tipo']],acoes:['arquivar']}
}

function Aviso({erro,ok}){return <>{erro&&<p className="alerta erro">{erro}</p>}{ok&&<p className="alerta sucesso">{ok}</p>}</>}

export function ListaModulo({tipo,admin=false}){
 const c=configs[tipo], [itens,setItens]=useState([]),[erro,setErro]=useState(''),[ok,setOk]=useState(''),[carregando,setCarregando]=useState(true)
 const carregar=()=>{setCarregando(true);return api.get(!admin&&c.publica?c.publica:c.api).then(setItens).catch(e=>setErro(e.message)).finally(()=>setCarregando(false))}
 useEffect(()=>{carregar()},[tipo,admin])
 const acoesValidas=x=>tipo==='oportunidades'?(x.situacao==='PLANEJADA'?['abrir','encerrar']:x.situacao==='ABERTA'?['encerrar']:[]):tipo==='acoes'?(x.situacao==='PLANEJADA'?['realizar','cancelar']:[]):tipo==='comunicados'?(x.situacao==='PUBLICADO'?['arquivar']:[]):[]
 async function agir(item,acao){if(!window.confirm(`Deseja realmente ${acao} "${item.titulo}"?`))return;try{await api.patch(`${c.api}/${item.id}/${acao}`);setOk('Operacao realizada.');await carregar()}catch(e){setErro(e.message)}}
 const vazio={oportunidades:'Nenhuma oportunidade disponivel.',acoes:'Nenhuma acao social disponivel.',comunicados:'Nenhum comunicado publicado.'}[tipo]||'Nenhum registro encontrado.'
 return <section><div className="titulo-pagina"><h1>{admin?'Gerir ':''}{c.titulo}</h1>{admin&&<Link className="botao primario" to={`/admin/${tipo}/nova`}>Novo cadastro</Link>}</div><Aviso erro={erro} ok={ok}/>
  {carregando?<div className="vazio">Carregando...</div>:itens.length===0?<div className="vazio">{vazio}</div>:<div className="grade-cartoes">{itens.map(x=><article className="cartao" key={x.id}><h2>{x.titulo}</h2><p>{x.descricao||x.conteudo}</p><p><span className="etiqueta">{x.situacao}</span></p>{x.livres!=null&&<p>Vagas livres: {x.livres}</p>}
   {admin&&<div className="acoes-form"><Link className="botao" to={`/admin/${tipo}/${x.id}`}>Editar</Link>{tipo==='oportunidades'&&<Link className="botao" to={`/admin/oportunidades/${x.id}/candidatos`}>Candidatos</Link>}{tipo==='acoes'&&<Link className="botao" to={`/admin/acoes/${x.id}/resultado`}>Resultado e vinculos</Link>}{acoesValidas(x).map(a=><button className={a==='cancelar'?'botao perigo':'botao'} key={a} onClick={()=>agir(x,a)}>{a}</button>)}</div>}
   {!admin&&tipo==='oportunidades'&&<Link className="botao primario" to={`/oportunidades/${x.id}`}>Ver e candidatar-se</Link>}{!admin&&tipo==='acoes'&&<Link className="botao" to={`/acoes/${x.id}`}>Ver detalhes</Link>}</article>)}</div>}</section>
}

export function FormModulo({tipo}){
 const c=configs[tipo],{id}=useParams(),nav=useNavigate(),[form,setForm]=useState({}),[erro,setErro]=useState(''),[salvando,setSalvando]=useState(false)
 useEffect(()=>{if(id)api.get(`${c.api}/${id}`).then(setForm).catch(e=>setErro(e.message))},[id,tipo])
 async function salvar(e){e.preventDefault();setSalvando(true);try{const corpo={...form};c.campos.filter(x=>x[2]==='number').forEach(x=>corpo[x[0]]=Number(corpo[x[0]]));if(tipo==='comunicados'&&!corpo.tipo)corpo.tipo='PUBLICO';id?await api.put(`${c.api}/${id}`,corpo):await api.post(c.api,corpo);nav(`/admin/${tipo}`)}catch(e){setErro(e.message)}finally{setSalvando(false)}}
 return <section><h1>{id?'Editar':'Novo'} {c.titulo}</h1><Aviso erro={erro}/><form className="cartao" onSubmit={salvar}>{c.campos.map(([nome,label,tipoCampo])=><div className="campo" key={nome}><label>{label}{!['idadeMinima','requisitos'].includes(nome)?' *':''}</label>{nome==='tipo'?<select value={form[nome]||'PUBLICO'} onChange={e=>setForm({...form,[nome]:e.target.value})}><option>PUBLICO</option><option>INTERNO</option></select>:['descricao','objetivo','requisitos','conteudo'].includes(nome)?<textarea required={!['requisitos'].includes(nome)} value={form[nome]??''} onChange={e=>setForm({...form,[nome]:e.target.value})}/>:<input type={tipoCampo||'text'} min={tipoCampo==='number'?0:undefined} required={!['idadeMinima','requisitos'].includes(nome)} value={form[nome]??''} onChange={e=>setForm({...form,[nome]:e.target.value})}/>}</div>)}<button className="botao primario" disabled={salvando}>{salvando?'Salvando...':'Salvar'}</button></form></section>
}

export function OportunidadeDetalhe(){const{id}=useParams(),[x,setX]=useState(),[msg,setMsg]=useState('');useEffect(()=>{api.get(`/api/oportunidades/${id}`).then(setX)},[id]);async function candidatar(){try{await api.post(`/api/candidaturas?oportunidadeId=${id}`);setMsg('Candidatura enviada.')}catch(e){setMsg(e.message)}}return <section><h1>{x?.titulo}</h1><p>{x?.descricao}</p><p>{x?.atividade} - {x?.local}</p><p>{x?.livres} vagas livres</p><button className="botao primario" onClick={candidatar}>Candidatar-se</button><p>{msg}</p></section>}

export function MinhasCandidaturas(){const[x,setX]=useState([]),[erro,setErro]=useState('');const carregar=()=>api.get('/api/candidaturas/minhas').then(setX).catch(e=>setErro(e.message));useEffect(()=>{carregar()},[]);async function cancelar(id){try{await api.patch(`/api/candidaturas/${id}/cancelar`);carregar()}catch(e){setErro(e.message)}}return <section><h1>Meu voluntariado</h1><Aviso erro={erro}/>{x.map(i=><article className="cartao" key={i.id}><h2>{i.oportunidadeTitulo}</h2><p>{i.situacao} {i.resultado&&`- ${i.resultado}`}</p>{['PENDENTE','APROVADA'].includes(i.situacao)&&<button className="botao" onClick={()=>cancelar(i.id)}>Cancelar</button>}</article>)}</section>}

export function MinhasDoacoes({admin=false}){const[x,setX]=useState([]),[erro,setErro]=useState('');const carregar=()=>api.get(admin?'/api/doacoes':'/api/doacoes/minhas').then(setX).catch(e=>setErro(e.message));useEffect(()=>{carregar()},[admin]);async function acao(id,a){try{await api.patch(`/api/doacoes/${id}/${a}`,a==='cancelar'&&admin?{motivo:prompt('Motivo:')}:undefined);carregar()}catch(e){setErro(e.message)}}return <section><h1>{admin?'Gerir doacoes':'Minhas doacoes'}</h1><Aviso erro={erro}/>{x.map(d=><article className="cartao" key={d.id}><h2>{d.item}</h2><p>{d.quantidade} - {d.situacao}</p><p>{d.usuarioNome}</p><div className="acoes">{admin&&d.situacao==='PENDENTE'&&<button className="botao" onClick={()=>acao(d.id,'confirmar')}>Confirmar</button>}{admin&&d.situacao==='CONFIRMADA'&&<button className="botao" onClick={()=>acao(d.id,'receber')}>Receber</button>}{['PENDENTE','CONFIRMADA'].includes(d.situacao)&&<button className="botao" onClick={()=>acao(d.id,'cancelar')}>Cancelar</button>}</div></article>)}</section>}

export function DoacaoForm(){const{id}=useParams(),nav=useNavigate(),[form,setForm]=useState({item:'',quantidade:1,observacao:'',formaEntrega:'ENTREGA_NA_INSTITUICAO'}),[erro,setErro]=useState('');async function salvar(e){e.preventDefault();try{await api.post('/api/doacoes',{...form,necessidadeId:Number(id),quantidade:Number(form.quantidade)});nav('/minhas-doacoes')}catch(e){setErro(e.message)}}return <section><h1>Registrar doacao</h1><Aviso erro={erro}/><form onSubmit={salvar}>{[['item','Item'],['quantidade','Quantidade','number'],['observacao','Observacao']].map(([n,l,t])=><div className="campo" key={n}><label>{l}</label><input type={t||'text'} value={form[n]} onChange={e=>setForm({...form,[n]:e.target.value})}/></div>)}<select value={form.formaEntrega} onChange={e=>setForm({...form,formaEntrega:e.target.value})}><option value="ENTREGA_NA_INSTITUICAO">Entrega na instituicao</option><option value="COMBINAR_ENTREGA">Combinar entrega</option></select><button className="botao primario">Doar</button></form></section>}

export function Transparencia(){const[x,setX]=useState({});useEffect(()=>{api.get('/api/transparencia').then(setX)},[]);return <section><h1>Transparencia</h1><div className="grade-cartoes">{Object.entries(x).map(([k,v])=><article className="cartao" key={k}><h2>{v}</h2><p>{k}</p></article>)}</div></section>}
export function Notificacoes(){const[x,setX]=useState([]);const carregar=()=>api.get('/api/notificacoes/minhas').then(setX);useEffect(()=>{carregar()},[]);return <section><h1>Minhas notificacoes</h1>{x.map(n=><article className="cartao" key={n.id}><p>{n.mensagem}</p><span>{n.estado}</span>{n.estado==='NAO_LIDA'&&<button className="botao" onClick={()=>api.patch(`/api/notificacoes/${n.id}/lida`).then(carregar)}>Marcar como lida</button>}</article>)}</section>}

export function CampanhaNecessidades(){const{id}=useParams(),[campanha,setCampanha]=useState(),[pagina,setPagina]=useState({content:[]}),[erro,setErro]=useState('');const carregar=()=>Promise.all([api.get(`/api/campanhas/${id}`),api.get('/api/necessidades')]).then(([c,n])=>{setCampanha(c);setPagina(n)}).catch(e=>setErro(e.message));useEffect(()=>{carregar()},[id]);async function vincular(nid){try{await api.post(`/api/campanhas/${id}/necessidades/${nid}`);carregar()}catch(e){setErro(e.message)}}async function remover(nid){try{await api.remove(`/api/campanhas/${id}/necessidades/${nid}`);carregar()}catch(e){setErro(e.message)}}return <section><h1>Necessidades de {campanha?.titulo}</h1><Aviso erro={erro}/><h2>Vinculadas</h2>{campanha?.necessidades?.map(n=><p key={n.id}>{n.titulo} <button className="botao" onClick={()=>remover(n.id)}>Desvincular</button></p>)}<h2>Disponiveis</h2>{pagina.content.map(n=><p key={n.id}>{n.titulo} <button className="botao" onClick={()=>vincular(n.id)}>Vincular</button></p>)}</section>}

export function CandidatosAdmin(){const{id}=useParams(),[x,setX]=useState([]),[erro,setErro]=useState('');const carregar=()=>api.get(`/api/oportunidades/${id}/candidaturas`).then(setX).catch(e=>setErro(e.message));useEffect(()=>{carregar()},[id]);async function agir(cid,a,corpo){try{await (a==='participacao'?api.post(`/api/candidaturas/${cid}/participacao`,corpo):api.patch(`/api/candidaturas/${cid}/${a}`,corpo));carregar()}catch(e){setErro(e.message)}}return <section><h1>Candidatos</h1><Aviso erro={erro}/>{x.map(c=><article className="cartao" key={c.id}><h2>{c.usuarioNome}</h2><p>{c.situacao} {c.resultado}</p>{c.situacao==='PENDENTE'&&<><button className="botao" onClick={()=>agir(c.id,'aprovar')}>Aprovar</button><button className="botao" onClick={()=>agir(c.id,'recusar',{motivo:'Recusada pelo administrador'})}>Recusar</button></>}{c.situacao==='APROVADA'&&!c.resultado&&<><button className="botao" onClick={()=>agir(c.id,'participacao',{resultado:'PRESENTE'})}>Presente</button><button className="botao" onClick={()=>agir(c.id,'participacao',{resultado:'AUSENTE'})}>Ausente</button></>}</article>)}</section>}

export function AcaoDetalhe({admin=false}){const{id}=useParams(),[x,setX]=useState(),[erro,setErro]=useState(''),[resultado,setResultado]=useState({descricaoResultado:'',beneficiadosReais:0});const carregar=()=>api.get(`/api/acoes/${id}`).then(setX).catch(e=>setErro(e.message));useEffect(()=>{carregar()},[id]);async function salvarResultado(e){e.preventDefault();try{await api.put(`/api/acoes/${id}/resultado`,{...resultado,beneficiadosReais:Number(resultado.beneficiadosReais)});carregar()}catch(e){setErro(e.message)}}async function upload(e){try{await api.upload(`/api/acoes/${id}/evidencias`,e.target.files[0]);carregar()}catch(e){setErro(e.message)}}return <section><h1>{x?.titulo}</h1><Aviso erro={erro}/><p>{x?.descricao}</p><p>{x?.local} - {x?.situacao}</p><p>Estimativa: {x?.estimativaBeneficiados} | Real: {x?.beneficiadosReais??'nao informado'}</p>{x?.descricaoResultado&&<p>{x.descricaoResultado}</p>}<h2>Evidencias</h2>{x?.evidencias?.map(ev=><p key={ev.id}><a href={`http://localhost:8080${ev.caminho}`} target="_blank">{ev.nomeArquivo}</a> {ev.publica?'Publica':'Privada'} {admin&&<button className="botao" onClick={()=>api.patch(`/api/evidencias/${ev.id}/visibilidade`).then(carregar)}>Alternar visibilidade</button>}</p>)}{admin&&<><form onSubmit={salvarResultado}><div className="campo"><label>Descricao do resultado</label><input value={resultado.descricaoResultado} onChange={e=>setResultado({...resultado,descricaoResultado:e.target.value})}/></div><div className="campo"><label>Beneficiados reais</label><input type="number" min="0" value={resultado.beneficiadosReais} onChange={e=>setResultado({...resultado,beneficiadosReais:e.target.value})}/></div><button className="botao primario">Salvar resultado</button></form><div className="campo"><label>Enviar evidencia</label><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={upload}/></div></>}</section>}
