import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { api, URL_API } from '../../servicos/api'

export default function AcaoDetalhePage({ admin = false }) {
  const { id } = useParams(), [acao, setAcao] = useState(null), [campanhas, setCampanhas] = useState([]), [necessidades, setNecessidades] = useState([]), [participacoes, setParticipacoes] = useState([])
  const [erro, setErro] = useState(''), [carregando, setCarregando] = useState(true), [resultado, setResultado] = useState({ descricaoResultado: '', beneficiadosReais: 0 })
  const carregar = async () => { setCarregando(true); try { const dados = await api.get(`/api/acoes/${id}`); setAcao(dados); setResultado({ descricaoResultado: dados.descricaoResultado || '', beneficiadosReais: dados.beneficiadosReais || 0 }); if (admin) { const [cs, ns, ps] = await Promise.all([api.get('/api/campanhas'), api.get('/api/necessidades'), api.get('/api/participacoes')]); setCampanhas(cs); setNecessidades(ns.content); setParticipacoes(ps) } } catch (e) { setErro(e.message) } finally { setCarregando(false) } }
  useEffect(() => { carregar() }, [id, admin])
  async function vincular(tipo, vinculoId) { try { await api.post(`/api/acoes/${id}/${tipo}/${vinculoId}`); await carregar() } catch (e) { setErro(e.message) } }
  async function desvincular(tipo, vinculoId) { if (!window.confirm('Remover este vinculo?')) return; try { await api.remove(`/api/acoes/${id}/${tipo}/${vinculoId}`); await carregar() } catch (e) { setErro(e.message) } }
  async function salvarResultado(e) { e.preventDefault(); try { await api.put(`/api/acoes/${id}/resultado`, { ...resultado, beneficiadosReais: Number(resultado.beneficiadosReais) }); await carregar() } catch (e) { setErro(e.message) } }
  async function upload(e) { try { await api.upload(`/api/acoes/${id}/evidencias`, e.target.files[0]); await carregar() } catch (e) { setErro(e.message) } }
  async function excluirEvidencia(ev) { if (!window.confirm(`Excluir a evidencia "${ev.nomeArquivo}"?`)) return; try { await api.remove(`/api/evidencias/${ev.id}`); await carregar() } catch (e) { setErro(e.message) } }
  if (carregando) return <div className="vazio">Carregando acao social...</div>
  if (!acao) return <p className="alerta erro">{erro || 'Acao social nao encontrada.'}</p>
  return <section><h1>{acao.titulo}</h1>{erro && <p className="alerta erro">{erro}</p>}<article className="cartao"><p>{acao.descricao}</p><p><strong>Objetivo:</strong> {acao.objetivo}</p><p><strong>Local:</strong> {acao.local}</p><p><strong>Periodo:</strong> {acao.dataInicio} a {acao.dataFim}</p><p><span className="etiqueta">{acao.situacao}</span></p><p>Estimativa: {acao.estimativaBeneficiados} | Real: {acao.beneficiadosReais ?? 'nao informado'}</p>{acao.descricaoResultado && <p>{acao.descricaoResultado}</p>}</article>
    <h2>Evidencias</h2>{acao.evidencias?.length ? acao.evidencias.map(ev => <p className="cartao" key={ev.id}><a href={`${URL_API}${ev.caminho}`} target="_blank" rel="noreferrer">{ev.nomeArquivo}</a> — {ev.publica ? 'Publica' : 'Privada'} {admin && <span className="acoes-inline"><button className="botao" onClick={() => api.patch(`/api/evidencias/${ev.id}/visibilidade`).then(carregar).catch(e => setErro(e.message))}>Alternar visibilidade</button><button className="botao perigo" onClick={() => excluirEvidencia(ev)}>Excluir</button></span>}</p>) : <div className="vazio">Nenhuma evidencia publicada.</div>}
    {admin && <>
      <div className="cartao"><h2>Campanhas vinculadas</h2>{acao.campanhas.map(cid => { const c = campanhas.find(x => x.id === cid); return <p key={cid}>{c?.titulo || `Campanha ${cid}`} <button className="botao pequeno" onClick={() => desvincular('campanhas',cid)}>Desvincular</button></p>})}<div className="acoes-form"><select id="campanha-vinculo" defaultValue=""><option value="" disabled>Selecione uma campanha</option>{campanhas.filter(c => !acao.campanhas.includes(c.id)).map(c => <option key={c.id} value={c.id}>{c.titulo}</option>)}</select><button className="botao" onClick={() => { const v=document.getElementById('campanha-vinculo').value; if(v)vincular('campanhas',v) }}>Vincular</button></div></div>
      <div className="cartao"><h2>Necessidades vinculadas</h2>{acao.necessidades.map(nid => { const n = necessidades.find(x => x.id === nid); return <p key={nid}>{n?.titulo || `Necessidade ${nid}`} <button className="botao pequeno" onClick={() => desvincular('necessidades',nid)}>Desvincular</button></p>})}<div className="acoes-form"><select id="necessidade-vinculo" defaultValue=""><option value="" disabled>Selecione uma necessidade</option>{necessidades.filter(n => !acao.necessidades.includes(n.id)).map(n => <option key={n.id} value={n.id}>{n.titulo}</option>)}</select><button className="botao" onClick={() => { const v=document.getElementById('necessidade-vinculo').value; if(v)vincular('necessidades',v) }}>Vincular</button></div></div>
      <div className="cartao"><h2>Participacoes vinculadas</h2>{(acao.participacoes || []).map(pid => { const p = participacoes.find(x => x.id === pid); return <p key={pid}>{p ? `${p.usuarioNome} — ${p.oportunidadeTitulo} (${p.resultado})` : `Participacao ${pid}`} <button className="botao pequeno" onClick={() => desvincular('participacoes',pid)}>Desvincular</button></p>})}<div className="acoes-form"><select id="participacao-vinculo" defaultValue=""><option value="" disabled>Selecione uma participacao registrada</option>{participacoes.filter(p => !(acao.participacoes || []).includes(p.id)).map(p => <option key={p.id} value={p.id}>{p.usuarioNome} — {p.oportunidadeTitulo} ({p.resultado})</option>)}</select><button className="botao" onClick={() => { const v=document.getElementById('participacao-vinculo').value; if(v)vincular('participacoes',v) }}>Vincular</button></div>{participacoes.length === 0 && <p className="vazio">Registre a presenca de candidatos aprovados para criar participacoes.</p>}</div>
      {acao.situacao === 'REALIZADA' && <form className="cartao" onSubmit={salvarResultado}><h2>Resultado</h2><div className="campo"><label>Descricao do resultado *</label><textarea required value={resultado.descricaoResultado} onChange={e => setResultado({...resultado,descricaoResultado:e.target.value})}/></div><div className="campo"><label>Beneficiados reais *</label><input required type="number" min="0" value={resultado.beneficiadosReais} onChange={e => setResultado({...resultado,beneficiadosReais:e.target.value})}/></div><button className="botao primario">Salvar resultado</button></form>}
      <div className="cartao"><h2>Enviar evidencia</h2><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={upload}/><small>JPEG, PNG ou PDF, ate 5 MB. Maximo de 5 arquivos.</small></div>
    </>}
  </section>
}
